import { useEffect, useMemo, useState } from 'react';
import { experiences } from './data/experiences';
import { Answers, HistoryState, Recommendation, WalkingLevel } from './types';
import { addValidation, completeExperience, lastCompletedId, loadHistory, startExperience } from './lib/history';
import { recommend } from './lib/recommend';
import { track } from './lib/analytics';
import QrScanner from './QrScanner';

type Screen='home'|'questions'|'results'|'detail'|'go'|'scan'|'return'|'done'|'history';
const defaultAnswers:Answers={time:60,returnTo:'彦根駅',interests:['歴史'],walking:'medium',budget:1000,firstVisit:true};
const walkLabel:Record<WalkingLevel,string>={low:'あまり歩かない',medium:'普通',high:'しっかり歩く'};

export default function App(){
 const [history,setHistory]=useState<HistoryState|null>(()=>loadHistory()); const [screen,setScreen]=useState<Screen>('home'); const [step,setStep]=useState(0); const [answers,setAnswers]=useState<Answers>(defaultAnswers); const [mode,setMode]=useState<'normal'|'continue'|'different'>('normal'); const [recs,setRecs]=useState<Recommendation[]>([]); const [selected,setSelected]=useState<Recommendation|null>(null); const [helpful,setHelpful]=useState<'great'|'okay'|'not'>('great'); const [counter,setCounter]=useState<'no'|'probablyNo'|'yes'>('probablyNo');
 useEffect(()=>{track('app_open'); if(history) track('returning_user_detected');},[]);
 const last=useMemo(()=>experiences.find(e=>e.id===lastCompletedId(history)),[history]);
 const runRecommendations=(m=mode,a=answers)=>{ const r=recommend(experiences,a,history,m); setRecs(r); setMode(m); setScreen('results'); track('recommendation_viewed',{count:r.length,mode:m}); };
 const beginQuestions=(m:'normal'|'continue'|'different'='normal')=>{setMode(m);setStep(0);setScreen('questions');track('questionnaire_started',{mode:m});};
 const selectRec=(r:Recommendation)=>{setSelected(r);setScreen('detail');track('recommendation_selected',{id:r.experience.id});};
 const beginExperience=()=>{ if(!selected) return; const h=startExperience({experienceId:selected.experience.id,startedAt:new Date().toISOString(),completed:false},answers); setHistory(h); setScreen('go');track('experience_started',{id:selected.experience.id}); };
 const markCompleted=(completed:boolean)=>{ if(!selected) return; if(completed){const h=completeExperience(selected.experience.id);setHistory(h);setScreen('done');track('experience_completed',{id:selected.experience.id,method:'manual'});} else {setScreen('home');track('experience_not_completed',{id:selected.experience.id});} };
 const markQrCompleted=()=>{ if(!selected) return; const h=completeExperience(selected.experience.id);setHistory(h);setScreen('done');track('qr_checkin_success',{id:selected.experience.id});track('experience_completed',{id:selected.experience.id,method:'qr'}); };
 const resetFlow=()=>{setSelected(null);setRecs([]);setScreen('home');};
 return <div className="app"><header className="top"><button className="brand" onClick={resetFlow}>次の彦根</button><span className="demo">デモデータ</span></header><main>
 {screen==='home' && <section className="hero cardless">{history && last ? <><p className="eyebrow">また彦根へ</p><h1>おかえりなさい。</h1><p>前回は「{last.name}」を体験しました。</p><div className="stack"><button className="primary" onClick={()=>{track('continue_previous_selected');beginQuestions('continue')}}>前回の続きを見る<span>前に見た彦根を、もう少し先へ。</span></button><button className="secondary" onClick={()=>{track('different_hikone_selected');beginQuestions('different')}}>今日は違う彦根を見る<span>前回とは別の彦根を歩いてみる。</span></button></div><button className="link" onClick={()=>setScreen('history')}>これまでに見た彦根</button></>:<><p className="eyebrow">彦根の次を選ぶ</p><h1>彦根城の次、<br/>どうする？</h1><p>残り時間と帰る場所から、<br/>今からできる彦根を選びます。</p><button className="primary" onClick={()=>beginQuestions()}>次の彦根を探す</button><p className="muted">おすすめをたくさん並べず、今のあなたに合うものを1〜3件だけ提案します。</p></>}</section>}
 {screen==='questions' && <Questionnaire step={step} setStep={setStep} answers={answers} setAnswers={setAnswers} onDone={()=>{track('questionnaire_completed');runRecommendations(mode,answers)}}/>}
 {screen==='results' && <section><p className="eyebrow">あなたへのおすすめ</p><h2>{recs.length?`${recs.length}件に絞りました`:'条件に合う候補がありません'}</h2>{!recs.length&&<><p>残り時間・予算・歩く量のどれかを少し広げてください。</p><button className="secondary" onClick={()=>beginQuestions(mode)}>条件を変える</button></>}<div className="cards">{recs.map(r=><button key={r.experience.id} className="exp-card" onClick={()=>selectRec(r)}><div><span className="pill">約{r.totalMinutes}分</span>{r.experience.sample&&<span className="pill">サンプル</span>}</div><h3>{r.experience.name}</h3><p>{r.experience.shortDescription}</p><p className="reason">{r.reason}</p><small>徒歩：{walkLabel[r.experience.walkingLevel]} ・ 予算目安：{r.experience.budgetMax===0?'無料':`〜${r.experience.budgetMax.toLocaleString()}円`}</small></button>)}</div></section>}
 {screen==='detail' && selected && <section><p className="eyebrow">この体験なら</p><h2>{selected.experience.name}</h2><p>{selected.experience.shortDescription}</p><div className="reason-box">{selected.reason}</div><div className="breakdown"><div><b>移動</b><span>{selected.travelOut}分</span></div><div><b>体験</b><span>{selected.experience.durationMinutes}分</span></div><div><b>{answers.returnTo}まで</b><span>{selected.travelBack}分</span></div><div><b>余裕</b><span>{selected.buffer}分</span></div></div><h3>合計 約{selected.totalMinutes}分</h3>{selected.experience.story&&<p>{selected.experience.story}</p>}{selected.experience.mission&&<div className="mission">小さなミッション<br/><b>{selected.experience.mission}</b></div>}<p className="note">このMVPの観光情報はサンプルです。営業時間・価格等は現地の最新情報を確認してください。</p><button className="primary" onClick={beginExperience}>これにする</button><button className="link" onClick={()=>setScreen('results')}>別のおすすめを見る</button></section>}
 {screen==='go' && selected && <section className="center"><p className="eyebrow">体験スタート</p><h1>いってらっしゃい。</h1><p>「{selected.experience.name}」へ向かいましょう。</p><div className="time-big">約{selected.totalMinutes}分</div><a className="secondary anchor" href={selected.experience.navigationUrl} target="_blank" rel="noreferrer" onClick={()=>track('navigation_clicked',{id:selected.experience.id})}>地図を開く</a><div className="checkpoint-box"><b>現地に着いたら</b><p>設置されているQRコードを読み取ると、その場所をめぐった記録が残ります。</p></div><button className="primary" onClick={()=>{setScreen('scan');track('qr_scanner_opened',{id:selected.experience.id});}}>現地のQRコードを読み取る</button><button className="link" onClick={()=>setScreen('return')}>QRコードが使えない場合</button></section>}
 {screen==='scan' && selected && <QrScanner experienceId={selected.experience.id} experienceName={selected.experience.name} onVerified={()=>markQrCompleted()} onCancel={()=>setScreen('go')}/>} 
 {screen==='return' && selected && <section className="center"><p className="eyebrow">代替チェック</p><h2>QRコードが使えない場合</h2><p>「{selected.experience.name}」には行けましたか？</p><p className="muted">実証時の予備導線です。通常は現地QRで訪問を確認します。</p><button className="primary" onClick={()=>markCompleted(true)}>行ってきた</button><button className="secondary" onClick={()=>markCompleted(false)}>今回は行かなかった</button><button className="link" onClick={()=>setScreen('go')}>戻る</button></section>}
 {screen==='done' && selected && <section className="center"><p className="eyebrow">今日の彦根</p><h2>またひとつ、彦根を知りました。</h2><div className="validation"><p>このおすすめは役に立ちましたか？</p><Choice value={helpful} setValue={setHelpful} options={[['great','とても役立った'],['okay','まあ役立った'],['not','あまり役立たなかった']]}/><p>このサービスがなければ、ここに行っていましたか？</p><Choice value={counter} setValue={setCounter} options={[['no','行かなかったと思う'],['probablyNo','たぶん行かなかった'],['yes','行ったと思う']]}/></div><button className="primary" onClick={()=>{setHistory(addValidation(selected.experience.id,helpful,counter)); runRecommendations('continue',answers); track('second_experience_selected');}}>もう少し歩く</button><button className="secondary" onClick={()=>{setHistory(addValidation(selected.experience.id,helpful,counter));setScreen('home')}}>今日はここまで</button><p className="muted">次に彦根へ来たときは、この続きから。</p></section>}
 {screen==='history' && <HistoryView history={history} onBack={()=>setScreen('home')} onNext={()=>beginQuestions('normal')}/>}
 </main><nav><button onClick={()=>setScreen('home')}>ホーム</button><button onClick={()=>beginQuestions('normal')}>次を探す</button><button onClick={()=>setScreen('history')}>これまでの彦根</button></nav></div>
}

function Questionnaire({step,setStep,answers,setAnswers,onDone}:{step:number;setStep:(n:number)=>void;answers:Answers;setAnswers:(a:Answers)=>void;onDone:()=>void}){
 const qs=[
  {q:'彦根であとどのくらい時間がありますか？', body:<Choice value={answers.time} setValue={(v)=>setAnswers({...answers,time:v as number})} options={[[30,'30分'],[60,'60分'],[90,'90分'],[120,'2時間以上']]}/>},
  {q:'最後にどこへ戻りますか？', body:<Choice value={answers.returnTo} setValue={(v)=>setAnswers({...answers,returnTo:v as string})} options={['彦根駅','彦根城周辺','京橋口駐車場','二の丸駐車場','その他'].map(x=>[x,x])}/>},
  {q:'今日は何が気になりますか？', body:<Multi values={answers.interests} setValues={v=>setAnswers({...answers,interests:v})} options={['歴史','街歩き','食','買い物','景色','地元らしさ','おまかせ']}/>},
  {q:'どのくらい歩けますか？', body:<Choice value={answers.walking} setValue={(v)=>setAnswers({...answers,walking:v as WalkingLevel})} options={[[ 'low','あまり歩きたくない'],['medium','普通'],['high','しっかり歩ける']]}/>},
  {q:'予算は？', body:<Choice value={answers.budget===null?'none':answers.budget} setValue={(v)=>setAnswers({...answers,budget:v==='none'?null:Number(v)})} options={[[0,'無料'],[1000,'1,000円以内'],[3000,'3,000円以内'],['none','特に決めていない']]}/>},
  {q:'彦根は初めてですか？', body:<Choice value={answers.firstVisit?'yes':'no'} setValue={(v)=>setAnswers({...answers,firstVisit:v==='yes'})} options={[[ 'yes','初めて'],['no','来たことがある']]}/>} 
 ];
 return <section><div className="progress"><span style={{width:`${((step+1)/qs.length)*100}%`}}/></div><p className="eyebrow">{step+1} / {qs.length}</p><h2>{qs[step].q}</h2>{qs[step].body}<div className="actions">{step>0&&<button className="link" onClick={()=>setStep(step-1)}>戻る</button>}<button className="primary" onClick={()=>step===qs.length-1?onDone():setStep(step+1)}>{step===qs.length-1?'おすすめを見る':'次へ'}</button></div></section>
}
function Choice({value,setValue,options}:{value:any;setValue:(v:any)=>void;options:any[][]}){return <div className="choice-grid">{options.map(([v,l])=><button key={String(v)} className={value===v?'choice active':'choice'} onClick={()=>setValue(v)}>{l}</button>)}</div>}
function Multi({values,setValues,options}:{values:string[];setValues:(v:string[])=>void;options:string[]}){return <div className="choice-grid">{options.map(v=><button key={v} className={values.includes(v)?'choice active':'choice'} onClick={()=>setValues(values.includes(v)?values.filter(x=>x!==v):[...values,v])}>{v}</button>)}</div>}
function HistoryView({history,onBack,onNext}:{history:HistoryState|null;onBack:()=>void;onNext:()=>void}){ const completed=(history?.visitHistory||[]).filter(v=>v.completed); return <section><p className="eyebrow">履歴</p><h2>これまでに見た彦根</h2>{completed.length===0?<p>まだ体験履歴はありません。</p>:completed.slice().reverse().map(v=>{const e=experiences.find(x=>x.id===v.experienceId);return e?<div className="history-item" key={v.startedAt}><small>{new Date(v.completedAt||v.startedAt).toLocaleDateString('ja-JP')}</small><h3>{e.name}</h3><p>{e.theme.join(' ・ ')}</p></div>:null})}<h3>まだ知らない彦根</h3><div className="tags"><span>湖</span><span>食</span><span>商い</span><span>路地</span><span>城下町</span></div><button className="primary" onClick={onNext}>次の彦根を探す</button><button className="link" onClick={onBack}>ホームへ戻る</button></section>}
