type JsonRecord=Record<string,unknown>;
const allowedNodeIds=['S01','D01','P01','P02'];
const allowedTags=['T_HIKONYAN','T_PHOTO','T_WALK','T_FOOD','T_SHOP','T_HISTORY','T_MODERN','T_ARCH','T_LAKE','T_SCENERY','T_STREETSCAPE','T_NATURE','T_RIVER','T_GARDEN'];
function setCors(res:any){res.setHeader('Access-Control-Allow-Origin',process.env.HIKONE_ALLOWED_ORIGIN||'*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS')}
function outputText(data:any):string{if(typeof data?.output_text==='string')return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&typeof c.text==='string')return c.text;return ''}
function parseJson(text:string):JsonRecord{return JSON.parse(text.trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim())}
async function callOpenAI(instructions:string,input:string){const key=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL;if(!key||!model)throw new Error('AI env missing');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model,instructions,input,max_output_tokens:800,store:false})});if(!r.ok)throw new Error('OpenAI '+r.status);const d=await r.json(),t=outputText(d);if(!t)throw new Error('No output');return parseJson(t)}
export default async function handler(req:any,res:any){setCors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 try{const {mode,message}=req.body||{};if(typeof message!=='string'||!message.trim())return res.status(400).json({error:'message required'});
  if(mode==='extract-v4'){const result=await callOpenAI([
   'You extract Hikone recommendation DB V4 user context only. Do not recommend places or invent data.',
   'Return JSON only: {"message":"short Japanese","answers":{"currentNodeId":string?,"finalNodeId":string?,"remainingTimeMin":number?,"interestTagIds":string[]?,"detourPreference":"最短|少しなら|積極"?,"discoveryOptIn":boolean?}}',
   'Allowed node ids: '+allowedNodeIds.join(', ')+'. Allowed tags: '+allowedTags.join(', ')+'. Omit unknown fields.'
  ].join('\n'),message);const raw:any=result.answers||{};const a:any={};if(allowedNodeIds.includes(raw.currentNodeId))a.currentNodeId=raw.currentNodeId;if(allowedNodeIds.includes(raw.finalNodeId))a.finalNodeId=raw.finalNodeId;if(Number.isFinite(raw.remainingTimeMin))a.remainingTimeMin=Math.round(raw.remainingTimeMin);if(Array.isArray(raw.interestTagIds))a.interestTagIds=raw.interestTagIds.filter((x:string)=>allowedTags.includes(x));if(['最短','少しなら','積極'].includes(raw.detourPreference))a.detourPreference=raw.detourPreference;if(typeof raw.discoveryOptIn==='boolean')a.discoveryOptIn=raw.discoveryOptIn;return res.status(200).json({message:typeof result.message==='string'?result.message:'条件を読み取りました。',answers:a})}
  if(mode==='present-v4'){const {candidates}=req.body||{};if(!Array.isArray(candidates))return res.status(400).json({error:'candidates required'});const result=await callOpenAI(['You are only a presentation layer. The V4 deterministic engine already decided feasibility. Never add/reorder places, travel times, actions or facts. Return JSON only: {"intro":"short Japanese","reasons":{"candidate-id":"short reason"}}'].join('\n'),JSON.stringify({message,candidates}));return res.status(200).json(result)}
  return res.status(400).json({error:'Unknown mode'});
 }catch(e){console.error(e);return res.status(502).json({error:'Hikone AI unavailable'})}}
